const today = new Date().toISOString().slice(0, 10);
const createdAt = new Date().toISOString();

export const mockTasks = [
  {
    id: 'task-morning-walk',
    title: 'Morning walk',
    completed: false,
    date: today,
    time: '07:30',
    category: 'Health',
    priority: 'medium',
    recurrence: 'daily',
    assignee: 'Me',
    notes: 'A short walk around the neighborhood.',
    createdAt,
    completedAt: null,
  },
  {
    id: 'task-project-brief',
    title: 'Finish project brief',
    completed: false,
    date: today,
    time: '10:00',
    category: 'Work',
    priority: 'high',
    recurrence: null,
    assignee: 'Me',
    notes: 'Send the first draft to the team.',
    createdAt,
    completedAt: null,
  },
  {
    id: 'task-laundry',
    title: 'Start a load of laundry',
    completed: false,
    date: today,
    time: null,
    category: 'Household',
    priority: 'low',
    recurrence: 'weekly',
    assignee: 'Me',
    notes: '',
    createdAt,
    completedAt: null,
  },
  {
    id: 'task-call-mum',
    title: 'Call Mum',
    completed: true,
    date: today,
    time: '18:30',
    category: 'Personal',
    priority: 'medium',
    recurrence: 'weekly',
    assignee: 'Me',
    notes: '',
    createdAt,
    completedAt: createdAt,
  },
];
