export const palettes = {
  softPink: {
    id: 'softPink',
    label: 'Soft Pink',
    colors: {
      background: '#FFF7F7',
      surface: '#FFFDFC',
      text: '#35252B',
      textSecondary: '#75666C',
      textMuted: '#998A90',
      primary: '#9B4D67',
      primarySoft: '#F6E5E9',
      accent: '#E8B6C3',
      border: '#E8D9DC',
      success: '#4B8A72',
      completed: '#EDF5F0',
      pattern: '#C9899E',
      categoryPersonal: '#F6E5E9',
      categoryWork: '#E7EFF8',
      categoryHousehold: '#FFF0DC',
      categoryHealth: '#E2F1E8',
    },
  },
  lavender: {
    id: 'lavender',
    label: 'Lavender',
    colors: {
      background: '#F8F7FC',
      surface: '#FFFFFF',
      text: '#2D2938',
      textSecondary: '#6E687A',
      textMuted: '#9891A4',
      primary: '#69538C',
      primarySoft: '#EEEAF7',
      accent: '#C8B9E3',
      border: '#E2DDEC',
      success: '#4A866D',
      completed: '#EDF5F0',
      pattern: '#9A88BC',
      categoryPersonal: '#EEEAF7',
      categoryWork: '#E4EFF8',
      categoryHousehold: '#FFF0DC',
      categoryHealth: '#E2F1E8',
    },
  },
  skyBlue: {
    id: 'skyBlue',
    label: 'Sky Blue',
    colors: {
      background: '#F3F9FC',
      surface: '#FFFFFF',
      text: '#20333C',
      textSecondary: '#5D717A',
      textMuted: '#8EA1AA',
      primary: '#2D6F8F',
      primarySoft: '#E1F0F7',
      accent: '#A8D2E4',
      border: '#D7E6EC',
      success: '#43826D',
      completed: '#EAF4EF',
      pattern: '#72AFC7',
      categoryPersonal: '#F0E8F8',
      categoryWork: '#E1F0F7',
      categoryHousehold: '#FFF0DC',
      categoryHealth: '#E2F1E8',
    },
  },
  sage: {
    id: 'sage',
    label: 'Sage',
    colors: {
      background: '#F4F8F2',
      surface: '#FFFFFF',
      text: '#27372D',
      textSecondary: '#607064',
      textMuted: '#8D9A90',
      primary: '#47745D',
      primarySoft: '#E4F0E7',
      accent: '#B4D0B9',
      border: '#DCE8DE',
      success: '#39745A',
      completed: '#E6F1E9',
      pattern: '#78A486',
      categoryPersonal: '#F0E8F8',
      categoryWork: '#E1EFFA',
      categoryHousehold: '#FFF0DC',
      categoryHealth: '#E2F1E8',
    },
  },
  warmBeige: {
    id: 'warmBeige',
    label: 'Warm Beige',
    colors: {
      background: '#FBF7F0',
      surface: '#FFFEFB',
      text: '#3B3027',
      textSecondary: '#75675B',
      textMuted: '#9E9185',
      primary: '#8A6347',
      primarySoft: '#F3E9DD',
      accent: '#DABFA2',
      border: '#E9DED2',
      success: '#5C8064',
      completed: '#EFF4EC',
      pattern: '#B18D6E',
      categoryPersonal: '#F1E8F8',
      categoryWork: '#E5EFF8',
      categoryHousehold: '#F8E9D5',
      categoryHealth: '#E4F0E5',
    },
  },
  peach: {
    id: 'peach',
    label: 'Peach',
    colors: {
      background: '#FFF7F2',
      surface: '#FFFEFC',
      text: '#3D2A24',
      textSecondary: '#7A645A',
      textMuted: '#A18C82',
      primary: '#A8563B',
      primarySoft: '#FCE8DE',
      accent: '#E9B39D',
      border: '#EEDBD1',
      success: '#4F846A',
      completed: '#EDF5EF',
      pattern: '#C77C61',
      categoryPersonal: '#F3E8F8',
      categoryWork: '#E3EFF8',
      categoryHousehold: '#FCEAD8',
      categoryHealth: '#E4F1E8',
    },
  },
  teal: {
    id: 'teal',
    label: 'Teal',
    colors: {
      background: '#F7F8F6',
      surface: '#FFFFFF',
      text: '#1D2A2F',
      textSecondary: '#536166',
      textMuted: '#7B878B',
      primary: '#2D6A6A',
      primarySoft: '#E5F0EE',
      accent: '#A7D0C7',
      border: '#E2E7E5',
      success: '#2F7D5A',
      completed: '#ECF5F0',
      pattern: '#72A59C',
      categoryPersonal: '#F2E8F8',
      categoryWork: '#E1EFFA',
      categoryHousehold: '#FFF0D8',
      categoryHealth: '#E0F3E8',
    },
  },
  deepBlue: {
    id: 'deepBlue',
    label: 'Deep Blue',
    colors: {
      background: '#F3F6FA',
      surface: '#FFFFFF',
      text: '#1D2936',
      textSecondary: '#5B6B7D',
      textMuted: '#8A99A8',
      primary: '#294C70',
      primarySoft: '#E3ECF5',
      accent: '#A9C2D9',
      border: '#D9E3EC',
      success: '#397B68',
      completed: '#EAF3EE',
      pattern: '#6F91B0',
      categoryPersonal: '#F0E8F8',
      categoryWork: '#E3ECF5',
      categoryHousehold: '#FFF0D8',
      categoryHealth: '#E0F2E8',
    },
  },
};

export const paletteList = Object.values(palettes);
